version: "3.9"

services:
  fastapi_services:
    build: ./fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


