version: "3.9"

services:
  ms_flota:
    build: ./Backend/MS-FLOTA
    container_name: ms_flota_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


